### ISSUE TITLE
"li" element indentation can be a problem

### ISSUE THREAD

**Issue by eloyesp** [judofyr/temple#105]
Pretty html adds indentation to all block elements, making sure that way that there is no visual change with that, but it is very common to make li elements display inline with css, making that indentation change affect the result (as it will add a space between the elements).

The main issue is that it will make results different when working on production and on development. I've already mentioned this in slim-template/slim#726 , but I've received no answer.

Have you got any idea?

**Comment by minad** [comment]
Closing, see https://github.com/slim-template/slim/issues/726#issuecomment-405055211.
