### ISSUE TITLE
CompiledDispatcher invokes Capistrano::Dsl#on

### ISSUE THREAD

**Issue by bughit** [judofyr/temple#130]
see capistrano/capistrano#2045

They should not be polluting Object but you can probably also be more selective with 

```rb
      def dispatched_methods
        re = /^on(_[a-zA-Z0-9]+)*$/
        self.methods.map(&:to_s).select(&re.method(:=~))
      end
```

**Comment by judofyr** [comment]
I haven't been that much involved in the design of the CompiledDispatcher so I don't know what a proper fix here is unfortunately.

**Comment by minad** [comment]
This should be fixed in Capistrano.
