### ISSUE TITLE
_temple_html_attributemerger1 with latest version of Temple

### ISSUE THREAD

**Issue by tristanoneil** [judofyr/temple#137]
Since https://github.com/judofyr/temple/commit/b0f1f6bdf8af8cbaa18f41d6cd080cc85cf27bb0 was introduced I'm getting `undefined local variable or method '_temple_html_attributeremover1'` when using Temple via Slim.

I'm open to submitting a PR with a fix but I'm not familiar enough with the Temple/Slim/Tilt gems to quite grasp why this commit is causing this error.

**Comment by judofyr** [comment]
To be fair I don't fully understand this either 😅
