### ISSUE TITLE
Release new Version - 0.9.2

### ISSUE THREAD

**Issue by rocket-turtle** [judofyr/temple#141]
Hey @minad,

thank you for picking up this gem.
I'm curently testing slim main branch with the temple 0.9.1 version and had some troubles.

Example - 
https://github.com/rocket-turtle/blog_7/commit/9ad2f723910c0cd6d9efd357f673429ac78c980b
```
- class_variable = 'foo'
#content class=class_variable
```

Renders:
```
curl http://127.0.0.1:3000/articles/index
<!DOCTYPE html><html><head></head><body><divfoo class="<!DOCTYPE html><html><head></head><body><divfoo class="" id="content"><p>Baa</p></div></body></html>%
```

Good thing is, this commit (https://github.com/judofyr/temple/commit/a25789dde93a6e0d5096b1c71f5ff5804e24ee14) seems to fix the problem.

Example -
https://github.com/rocket-turtle/blog_7/commit/63ecc11aeb0a295655bba2e705a933861eeceaaf

Renders:
```
$ curl http://127.0.0.1:3000/articles/index
<!DOCTYPE html><html><head></head><body><div class="foo" id="content"><p>Baa</p></div></body></html>%
```

So would you mind releasing a new Version or is there anything else to do?
https://github.com/judofyr/temple/compare/v0.9.1...master

**Comment by minad** [comment]
A new release is planned soon.

**Comment by rocket-turtle** [comment]
[0.10.0](https://rubygems.org/gems/temple/versions/0.10.0) - January 23, 2023 (40 KB)

Thank you.
