### ISSUE TITLE
Upgrading Temple 0.10.0 to 0.10.1 failed my Slim templates

### ISSUE THREAD

**Issue by olleolleolle** [judofyr/temple#145]
Hello,

Apologies. This is a bug report with fuzzy edges.

I updated temple to 0.10.1 from 0.10.0 and I got a 

> NoMethodError: undefined method `empty?' for nil:NilClass

in [Sinatra](https://github.com/sinatra/sinatra/blob/v3.0.6/lib/sinatra/base.rb#L947):

> [GEM_ROOT]/gems/sinatra-3.0.6/lib/sinatra/base.rb:947 :in `__tilt_9660`

Hmm. I pinned temple to 0.10.0, and went on with my day.

I registered [a note in the Sinatra Discussions](https://github.com/sinatra/sinatra/discussions/1925).

**Comment by scivola** [comment]
I also found this problem.

Here is a minimal reproduction code:

```rb
gem "sinatra", "3.0.6"
gem "slim", "5.1.1"
gem "temple", "0.10.1"

require "sinatra"

get "/" do
  slim %(div class="" foo)
end
```

When we access http://localhost:4567/, we will see `NoMethodError`.

The exception will be gone by one of the following change:

* temple version: 0.10.1 -> 0.10.0
* change `class` to other attribute, for example `style`, `lang`, `id`
* change values of `class` to other (but `nil` and `false` are same as `""`)

**Comment by scivola** [comment]
In version 0.10.1, argument `**options` was added to the line https://github.com/judofyr/temple/blob/22072c8fbf3b437a7197d77064b80786a056be6e/lib/temple/generator.rb#L58

I found that if `options[:save_buffer]` is `false`, the exception will not raise.

**Comment by minad** [comment]
Can you please confirm that https://github.com/judofyr/temple/commit/0bdacf93e87294e6dd2935c6178071329fa2bcda fixes the issue successfully for you?

**Comment by scivola** [comment]
https://github.com/judofyr/temple/commit/0bdacf93e87294e6dd2935c6178071329fa2bcda fixes it certainly.
Thank you very much.

**Comment by minad** [comment]
Thanks, I tagged version 0.10.2.

**Comment by olleolleolle** [comment]
Oh, many thanks, you wonderful people 🙏!
