### ISSUE TITLE
Consider not shipping specs in gem

### ISSUE THREAD

**Issue by jeremyevans** [judofyr/temple#146]
Currently, if you install the gem and try to run the specs, it fails because bundler tries to load the gemspec, which tries to run git, which fails because there is no git repository.

There are two possible approaches:

1. Make specs runnable from the gem (e.g. not depend on the git repository)
2. Remove specs from gem

Approach 2 seems to be preferred by most gems these days, because it also reduces the size of the gem, making it faster to install, and almost nobody actually runs the specs for downloaded gems.

**Comment by k0kubun** [comment]
Removed in v0.10.3.
