### ISSUE TITLE
Generator supports only core expressions - found [false, false, false]

### ISSUE THREAD

**Issue by gazay** [judofyr/temple#85]
Hello,

We started seeing this issue about month ago randomly on different servers with different environments (rails 4.0.12, 4.0.13 and rails 4.2). Some of requests throws that exception on random templates and if I repeat those falling requests several times with curl, with the same session, cookies – error doesn't present. Full backtrace here: https://gist.github.com/gazay/f27860236dc8a11ec16d.

According to dates of first error all what we change – we added new asset compilation environment on node.js. But I don't see how it can affect slim templates (or temple if bug is there).

Our Gemfile is here: https://gist.github.com/gazay/c7884ec890448ceaeacf

Do you have any idea what can trigger this kind of exception? I can provide other info if needed, but failing templates are totally random, even simple footer partial without any logic fail once.

**Comment by minad** [comment]
Could you create a small rails app which shows the problem? It means that something goes wrong during the compilation and invalid expressions are generated. But I don't have an idea where this happens.

**Comment by gazay** [comment]
I can't reproduce it locally, so I think I can't create small app which will reproduce this bug. I thought maybe someone seen this before or knows how some of environment parts can cause this behavior like some unicorn bug or other component. I spent like two days in tracing this error, get logs from everywhere, looked through all flow with debugger locally (but without reproduced error it gives me nothing except that).

**Comment by minad** [comment]
Ok, can you print out the abstract syntax tree (nested array of expressions) parsed by slim at different stages of the engine pipeline? Take a look at Temple::Engine#call. You could add a debug output there and identify the problematic filter which creates the invalid expression [false, false, false]. Are you familiar with how temple works in general?

**Comment by gazay** [comment]
Yep, I know and I already put debug output there. But right now we upgrade our production servers to rails 4.2 and long time I don't see this error. Anyway debugging output in several places of rendering flow and if it happens again I'll post it here. If not – I'll just close this issue tomorrow. Thank you!

**Comment by gazay** [comment]
Here the gist from error: https://gist.github.com/gazay/cb57a3f45492ddded301.
It seems that problematic node is here https://gist.github.com/gazay/cb57a3f45492ddded301#file-ast-rb-L237 which in template equals this line: https://gist.github.com/gazay/cb57a3f45492ddded301#file-input-slim-L50

**Comment by minad** [comment]
Thx. Unfortunately this doesn't really help me enough. Could you add a debug output before/after each filter step? This would help to identify where the invalid expression is generated. From what you sent me, I only see that it is there but not where it was produced.

**Comment by minad** [comment]
At the line where the `[false, false]` is there should be ` [:code, "#{tmp}.reject!(&:empty?)"]`. Something weird is going on here. See https://github.com/slim-template/slim/blob/master/lib/slim/code_attributes.rb#L59

**Comment by gazay** [comment]
Here another error with same strange behavior but in different filter: https://gist.github.com/gazay/45903603c1e413815109#file-ast-rb-L10 from here https://gist.github.com/gazay/45903603c1e413815109#file-template-slim-L7. Instead of [:code, "..."] – [false, false]. I'll try to get all places where it happened and try to store some information right inside filters. Don't know how yet, but I'll try

**Comment by minad** [comment]
I recommend that you go to Temple::Engine#call. There you can print out the expression before/after each filter. If we know the problematic filter we can continue from there.

**Comment by gazay** [comment]
You right, I'm a little bit slow. I've added store to get all before/after info for each filter. As it happened again I'll add it here

**Comment by minad** [comment]
If it doesn't happen all the time, it is probably some threading issue or something similar. Could you tell me more about your setup? Is there anything special?

**Comment by gazay** [comment]
Yes, I think the same. I'm right now in reading huge outputs from filters, trying to figure out maybe there are same point for every error. But seems like that is not true, different filters for different errors. I'll update status later

**Comment by gazay** [comment]
1. gist: https://gist.github.com/gazay/edd16a48919cb745085e
    filter Slim#Parser
    wrong line in template https://gist.github.com/gazay/edd16a48919cb745085e#file-template-slim-L79
    wrong node in parsed ast: https://gist.github.com/gazay/edd16a48919cb745085e#file-ast_after_slim-parser-rb-L538

2. gist https://gist.github.com/gazay/98990c371771de7f0b41
    filter Template#Pretty
    wrong line in template: https://gist.github.com/gazay/98990c371771de7f0b41#file-template-slim-L12
    wrong line in before: https://gist.github.com/gazay/98990c371771de7f0b41#file-before-template-pretty-rb-L224
    wrong line in after: https://gist.github.com/gazay/98990c371771de7f0b41#file-after-template-pretty-rb-L264

3. gist https://gist.github.com/gazay/7e56870eae527294df8f
    filter Template#Pretty
    wrong line in template: https://gist.github.com/gazay/7e56870eae527294df8f#file-template-slim-L71
    wrong line in before: https://gist.github.com/gazay/7e56870eae527294df8f#file-before-slim-splat-filter-rb-L250
    wrong line in after: https://gist.github.com/gazay/7e56870eae527294df8f#file-after-slim-splat-filter-rb-L250

**Comment by minad** [comment]
Ok, this is weird. The problem occurs somehow non deterministically, right? Maybe this is a bug of the expression dispatcher in temple, see Temple::Mixins::CompiledDispatcher. You could replace that one with an older variant which is not compiled (see git log for an older version).

If it is not that I don't think it is a Slim/Temple bug. Maybe it's a problem of the interpreter. Could you check which version of Slim/Temple/Rails/Ruby introduced this? In that case, I would recommend that you fix all versions to the newest one and then test different ruby interpreter versions while keeping the other versions fixed, after that change the version of something else and keep the rest fixed.

**Comment by gazay** [comment]
Do you mean to replace Temple::Mixins::CompiledDispatcher with this code? https://github.com/judofyr/temple/commit/a04cdd96dba50f65fd3f6b600011c6229c4d1ddf
I'll try, thank you.
About interpreter – we used before error 2.1.5, then we switch to 2.2.0 and a week ago we switched to 2.2.1p85, so it seems this problem is not from interpreter.

**Comment by minad** [comment]
Any news on that?

**Comment by gazay** [comment]
Oh, yes, it was bug in nokogiri: https://github.com/sparklemotion/nokogiri/issues/1270. Sorry, I forgot about this issue, closing now. Thank you for help again! It was interesting to find this bug :)

**Comment by flavorjones** [comment]
Hmm, just following up, this isn't a bug in Nokogiri -- the libxml-ruby gem wires itself into the libxml2 memory management hooks and prevents Nokogiri from doing the right thing.

Don't use libxml-ruby and nokogiri at the same time, it's not supported. Thanks.
